version: '3.9'
services:
  db:
    container_name: postgres_container
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: admin  
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: mydb
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"